"""add_kyc_workflow_tables

Revision ID: bf6af1710f97
Revises: 612c6569cfe6
Create Date: 2026-01-19 15:27:36.317637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf6af1710f97'
down_revision: Union[str, Sequence[str], None] = '612c6569cfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_verifications_farmer_id', 'external_verifications', ['farmer_id'])
    op.create_index('ix_external_verifications_type', 'external_verifications', ['verification_type'])
    op.create_table('kyc_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('personal_info_complete', sa.Boolean(), nullable=False),
    sa.Column('documents_complete', sa.Boolean(), nullable=False),
    sa.Column('biometrics_complete', sa.Boolean(), nullable=False),
    sa.Column('bank_info_complete', sa.Boolean(), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_biometrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_biometrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id_verification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credit_check_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sanctions_check_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_table('kyc_review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_review_queue_status', 'kyc_review_queue', ['status'])
    op.create_index('ix_kyc_review_queue_assigned_to', 'kyc_review_queue', ['assigned_to'])
    op.create_index('ix_kyc_review_queue_priority', 'kyc_review_queue', ['priority'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kyc_review_queue_priority', table_name='kyc_review_queue')
    op.drop_index('ix_kyc_review_queue_assigned_to', table_name='kyc_review_queue')
    op.drop_index('ix_kyc_review_queue_status', table_name='kyc_review_queue')
    op.drop_table('kyc_review_queue')
    op.drop_table('kyc_applications')
    op.drop_index('ix_external_verifications_type', table_name='external_verifications')
    op.drop_index('ix_external_verifications_farmer_id', table_name='external_verifications')
    op.drop_table('external_verifications')
    # ### end Alembic commands ###
